language: python
python:
  - 2.7
cache: pip
install:
  - pip install yara-python
  - pip install psutil
  - pip install colorama
  - pip install pylzma
  - pip install netaddr
  - pip install pycrypto
  - pip install rfc5424-logging-handler

script:
  - python ./loki.py --noprocs --noindicator --dontwait --debug -p ./test
  - python ./loki.py --noprocs --noindicator --dontwait --debug --intense -p ./test
  - python ./loki.py --noprocs --noindicator --dontwait --debug --csv -p ./test

notifications:
  email:
    recipients:
      - venom14@gmail.com
    on_success: never
    on_failure: always
